use_frameworks!

platform :ios, '10.0'
inhibit_all_warnings!

target 'begateway_Example' do
  pod 'begateway', :path => '../'
#  pod 'Alamofire', '~> 5.0.0-beta.5'

  target 'begateway_Tests' do
    inherit! :search_paths

    
  end
end
